# Generated by Django 5.2.17 on 2026-08-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selahcue_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('DEMO', 'Demo'), ('TRIAL', 'Trial'), ('PILOT', 'Pilot'), ('PAID', 'Paid'), ('INTERNAL_QA', 'Internal QA'), ('CUSTOM', 'Custom')], max_length=32)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('ACTIVATED', 'Activated'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('CONVERTED', 'Converted'), ('ARCHIVED', 'Archived')], default='ISSUED', max_length=32)),
                ('key_prefix', models.CharField(max_length=32)),
                ('key_suffix', models.CharField(max_length=16)),
                ('masked_key', models.CharField(max_length=64)),
                ('secret_hash', models.CharField(max_length=256)),
                ('secret_fingerprint', models.CharField(max_length=64, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('feature_scope', models.CharField(max_length=64)),
                ('seat_limit', models.PositiveIntegerField(default=1)),
                ('device_limit', models.PositiveIntegerField(default=1)),
                ('territory', models.CharField(blank=True, max_length=32)),
                ('generated_by_actor_id', models.CharField(max_length=128)),
                ('generated_reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_keys', to='selahcue_accounts.customerorg')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'status', 'expires_at'], name='selahcue_li_custome_4a5253_idx'), models.Index(fields=['key_prefix'], name='selahcue_li_key_pre_0b3fd2_idx'), models.Index(fields=['key_suffix'], name='selahcue_li_key_suf_6ae2d6_idx'), models.Index(fields=['key_type', 'status'], name='selahcue_li_key_typ_73e9a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('generated_by_actor_id', 'idempotency_key'), name='uniq_license_key_actor_idempotency'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='license_key_expires_after_start')],
            },
        ),
    ]
