# Generated by Django 6.1 on 2026-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_accounts', '0003_credentialtoken_customersession'),
        ('selahcue_license_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicensekey',
            name='prior_status',
            field=models.CharField(blank=True, choices=[('ISSUED', 'Issued'), ('ACTIVATED', 'Activated'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('CONVERTED', 'Converted'), ('ARCHIVED', 'Archived')], default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='applicensekey',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUSPENDED'), models.Q(('prior_status', ''), _negated=True)), models.Q(models.Q(('status', 'SUSPENDED'), _negated=True), ('prior_status', '')), _connector='OR'), name='license_key_prior_status_iff_suspended'),
        ),
    ]
