# Generated by Django 6.1 on 2026-08-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_license_keys', '0002_applicensekey_prior_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicensekey',
            name='seat_limit',
        ),
    ]
