# Generated by Django 5.2.17 on 2026-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('CHURNED', 'Churned'), ('ARCHIVED', 'Archived')], default='PROSPECT', max_length=32)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('plan', models.CharField(default='TRIAL', max_length=64)),
                ('seat_limit', models.PositiveIntegerField(default=1)),
                ('device_limit', models.PositiveIntegerField(default=1)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_by_actor_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'country'], name='selahcue_ac_status_83d172_idx'), models.Index(fields=['slug'], name='selahcue_ac_slug_c23765_idx'), models.Index(fields=['primary_contact_email'], name='selahcue_ac_primary_5ab022_idx')],
                'constraints': [models.UniqueConstraint(fields=('created_by_actor_id', 'idempotency_key'), name='uniq_customer_org_actor_idempotency')],
            },
        ),
    ]
