# Generated by Django 5.2.17 on 2026-08-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_fingerprint', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='INVITED', max_length=32)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MEMBER', 'Member')], default='MEMBER', max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_by_actor_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='selahcue_accounts.customerorg')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'status'], name='selahcue_ac_custome_592ff7_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='uniq_customer_user_email'), models.UniqueConstraint(fields=('email_fingerprint',), name='uniq_customer_user_email_fp'), models.UniqueConstraint(fields=('created_by_actor_id', 'idempotency_key'), name='uniq_customer_user_actor_idempotency')],
            },
        ),
    ]
