# Generated by Django 5.2.17 on 2026-08-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_accounts', '0002_customeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFY', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], max_length=32)),
                ('token_hash', models.CharField(max_length=256)),
                ('token_fingerprint', models.CharField(max_length=64, unique=True)),
                ('masked_token', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_tokens', to='selahcue_accounts.customeruser')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_user', 'purpose'], name='selahcue_ac_custome_df13ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_prefix', models.CharField(max_length=32)),
                ('token_suffix', models.CharField(max_length=16)),
                ('masked_token', models.CharField(max_length=64)),
                ('token_hash', models.CharField(max_length=256)),
                ('token_fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='selahcue_accounts.customeruser')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_user', 'status'], name='selahcue_ac_custome_5cef41_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='customer_session_expires_after_issue')],
            },
        ),
    ]
