# Generated by Django 6.1 on 2026-08-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_accounts', '0003_credentialtoken_customersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorg',
            name='seat_limit',
        ),
    ]
