# Generated by Django 5.2.17 on 2026-08-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selahcue_accounts', '0001_initial'),
        ('selahcue_license_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_public_id', models.CharField(max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=32)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('activated_by_actor_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='selahcue_accounts.customerorg')),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='selahcue_license_keys.applicensekey')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_prefix', models.CharField(max_length=32)),
                ('token_suffix', models.CharField(max_length=16)),
                ('masked_token', models.CharField(max_length=64)),
                ('token_hash', models.CharField(max_length=256)),
                ('token_fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='selahcue_devices.device')),
            ],
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['license_key', 'status'], name='selahcue_de_license_ce8a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['customer', 'status'], name='selahcue_de_custome_9fded6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_public_id'], name='selahcue_de_device__754d46_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('license_key', 'idempotency_key'), name='uniq_device_key_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('license_key', 'device_fingerprint'), name='uniq_device_license_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['device', 'status'], name='selahcue_de_device__620e35_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicetoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='device_token_expires_after_issue'),
        ),
    ]
