# Generated by Django 6.1 on 2026-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selahcue_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['status'], name='device_token_status_idx'),
        ),
    ]
