//! Compile-time verse-run tables for the bundled translations (86ak84fbd).
//!
//! The operator's view build asks, for every scripture link in the plan and after every command
//! (Blackout and Clear included), "does this passage present at least one verse?". Answering
//! that from the runtime verse index means gunzipping and parsing a whole translation (~4 MB of
//! text, ~31k `String`s) the first time any passage of it is asked about — a cost that landed on
//! the emergency controls. The question only needs to know WHICH verse numbers exist in each
//! chapter, so this script reads the same gzipped assets the crate embeds and writes that — as a
//! sorted list of `(book, chapter, first verse, last verse)` runs — into a `static` slice. At
//! runtime the answer is a binary search over ~1.2k eight-byte rows: no decompression, no
//! allocation, no cache.
//!
//! A run, not a verse count, because translations disagree about which verses exist: the WEB has
//! no Luke 17:36 but does have 17:37, so a count of 36 would call 17:37 missing and 17:36
//! present. Contiguous verses collapse to one run (the KJV is one run per chapter, 1189 rows);
//! each omitted verse adds one.
//!
//! The table is derived from the shipped bytes at build time, so it cannot go stale when an
//! asset is replaced. The line grammar is shared with the runtime decoder (`src/tsv_row.rs`,
//! pulled in below by path), so the two cannot disagree about which lines are verses.
//!
//! A decode failure here is a build defect — the runtime decoder degrades to an empty index
//! instead of panicking, but a corrupt embedded asset should fail the BUILD, not ship.

use flate2::read::GzDecoder;
use std::fmt::Write as _;
use std::io::Read as _;
use std::path::PathBuf;
use std::{env, fs};

#[path = "src/tsv_row.rs"]
mod tsv_row;

/// `(static name in the generated file, asset file stem)` — one per BUNDLED translation. A
/// downloadable translation has no embedded asset and so no table. Adding a bundled translation
/// means adding it here AND to `versification::runs_of`; forgetting either is a compile error,
/// not a silent gap (the generated `static` is referenced by name, and the match is exhaustive).
const BUNDLED: [(&str, &str); 5] = [
    ("KJV", "kjv"),
    ("WEB", "web"),
    ("ASV", "asv"),
    ("WEBBE", "webbe"),
    ("DBY", "dby"),
];

/// Hard ceiling on rows per translation — a tripwire, not a tuning knob. Real tables are
/// 1189–1205 rows; a table past this means the asset stopped looking like a Bible (or the run
/// merge broke) and the "tiny, fixed-size" premise this module exists on is gone. Fails the
/// build rather than quietly shipping a large table.
const MAX_RUNS: usize = 2048;

type Run = (u8, u16, u16, u16);

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/tsv_row.rs");

    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));

    let mut generated = String::from(
        "// @generated by build.rs from assets/*.tsv.gz — do not edit; see build.rs.\n\n",
    );
    for (name, stem) in BUNDLED {
        let asset = manifest.join("assets").join(format!("{stem}.tsv.gz"));
        println!("cargo:rerun-if-changed={}", asset.display());

        let compressed = fs::read(&asset)
            .unwrap_or_else(|e| panic!("cannot read bundled asset {}: {e}", asset.display()));
        let mut tsv = String::new();
        GzDecoder::new(compressed.as_slice())
            .read_to_string(&mut tsv)
            .unwrap_or_else(|e| panic!("bundled asset {} does not decode: {e}", asset.display()));

        let runs = runs_of(&tsv);
        assert!(
            !runs.is_empty(),
            "bundled asset {} has no verse lines",
            asset.display()
        );
        assert!(
            runs.len() <= MAX_RUNS,
            "bundled asset {} produced {} verse runs (cap {MAX_RUNS}) — it no longer looks like a \
             Bible, or the run merge is broken",
            asset.display(),
            runs.len()
        );

        writeln!(
            generated,
            "/// {name}: {} verse runs (book, chapter, first verse, last verse), sorted.\n\
             pub(crate) static {name}: &[Run] = &[",
            runs.len()
        )
        .expect("write to String");
        for (book, chapter, first, last) in runs {
            writeln!(generated, "    ({book}, {chapter}, {first}, {last}),")
                .expect("write to String");
        }
        generated.push_str("];\n\n");
    }
    fs::write(out_dir.join("verse_runs.rs"), generated).expect("write verse_runs.rs");
}

/// Maximal runs of consecutive verse numbers per `(book, chapter)`, sorted. Reads lines through
/// the SAME parser as the runtime decoder, so a malformed line is dropped here iff it is dropped
/// there.
fn runs_of(tsv: &str) -> Vec<Run> {
    let mut verses: Vec<(u8, u16, u16)> = tsv
        .lines()
        .filter_map(|line| tsv_row::parse_row(line).map(|(b, c, v, _)| (b, c, v)))
        .collect();
    verses.sort_unstable();
    verses.dedup();

    let mut runs: Vec<Run> = Vec::new();
    for (book, chapter, verse) in verses {
        match runs.last_mut() {
            // Adjacent in the same chapter: extend the run. `u32` so a verse numbered
            // `u16::MAX` cannot overflow the comparison.
            Some((b, c, _, last))
                if *b == book && *c == chapter && u32::from(verse) == u32::from(*last) + 1 =>
            {
                *last = verse;
            }
            _ => runs.push((book, chapter, verse, verse)),
        }
    }
    runs
}
