# Generated by Django 5.2.17 on 2026-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_kind', models.CharField(max_length=32)),
                ('actor_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=96)),
                ('target_type', models.CharField(max_length=96)),
                ('target_id', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILED', 'Failed')], default='SUCCESS', max_length=32)),
                ('request_id', models.CharField(max_length=128)),
                ('source_surface', models.CharField(default='admin_graphql', max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['actor_id', 'created_at'], name='selahcue_au_actor_i_9ba95e_idx'), models.Index(fields=['target_type', 'target_id', 'created_at'], name='selahcue_au_target__d631d8_idx'), models.Index(fields=['action', 'created_at'], name='selahcue_au_action_9b562c_idx'), models.Index(fields=['request_id'], name='selahcue_au_request_3044a0_idx')],
            },
        ),
    ]
