# Generated by Django 6.1 on 2026-08-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selahcue_license_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('BOOLEAN', 'Boolean flag'), ('INTEGER', 'Integer count')], max_length=16)),
                ('default_raw_value', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('governs_instance_limit', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='selahcue_ca_is_acti_2982cb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('governs_instance_limit', True)), fields=('governs_instance_limit',), name='uniq_catalogue_instance_limit_dimension')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('is_public', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'sort_order'], name='selahcue_ca_status_f27519_idx'), models.Index(fields=['code'], name='selahcue_ca_code_0989db_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_fallback', True)), fields=('is_fallback',), name='uniq_catalogue_fallback_plan')],
            },
        ),
        migrations.CreateModel(
            name='LicensePlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by_actor_id', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_plan_assignment', to='selahcue_license_keys.applicensekey')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='selahcue_catalogue.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanScopeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_scope', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_aliases', to='selahcue_catalogue.plan')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseGrantOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='selahcue_catalogue.grantdimension')),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_grant_overrides', to='selahcue_license_keys.applicensekey')),
            ],
            options={
                'indexes': [models.Index(fields=['license_key'], name='selahcue_ca_license_28f1c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('license_key', 'dimension'), name='uniq_catalogue_license_grant_override')],
            },
        ),
        migrations.CreateModel(
            name='PlanGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='selahcue_catalogue.grantdimension')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='selahcue_catalogue.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['plan'], name='selahcue_ca_plan_id_2033b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'dimension'), name='uniq_catalogue_plan_grant')],
            },
        ),
    ]
